Repository anchore/vunnel, pull requests merged in 2023-10, with the labels that each got.

#322 chore: add missing ubuntu namespaces to quality test
  tests/quality/config.yaml
Labels: changelog-ignore

#337 chore: add snapshot tests to Amazon provider
  src/vunnel/providers/amazon/parser.py
  tests/unit/providers/amazon/test-fixtures/snapshots/amzn:2/alas-2018-939.json
  tests/unit/providers/amazon/test-fixtures/snapshots/amzn:2022/alas-2021-001.json
  tests/unit/providers/amazon/test-fixtures/snapshots/amzn:2023/alas-2023-126.json
  tests/unit/providers/amazon/test_amazon.py
Labels: provider:amazon, run-pr-quality-gate

#340 Add snapshot tests for NVD provider
  tests/conftest.py
  tests/unit/providers/nvd/test-fixtures/full-page.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2021/cve-2021-20581.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2021/cve-2021-29913.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2021/cve-2021-38859.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-22375.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-22377.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-22380.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-22384.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-22385.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-43889.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-43891.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2022/cve-2022-43893.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-20261.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-22068.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-27314.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-30781.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-3706.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-3707.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-3746.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-43250.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45109.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45383.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45391.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45602.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45604.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45607.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45628.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45630.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45632.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45901.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45902.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45903.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45904.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45905.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45906.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-45907.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-46009.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-5631.json
  tests/unit/providers/nvd/test-fixtures/snapshots/full-page/2023/cve-2023-5642.json
  tests/unit/providers/nvd/test-fixtures/snapshots/single-entry/2011/cve-2011-0022.json
  tests/unit/providers/nvd/test_nvd.py
Labels: run-pr-quality-gate

#341 Add snapshot tests for oracle provider
  src/vunnel/providers/oracle/parser.py
  tests/unit/providers/oracle/test-fixtures/snapshots/ol:5/elsa-2007-0057.json
  tests/unit/providers/oracle/test-fixtures/snapshots/ol:6/elsa-2018-4250.json
  tests/unit/providers/oracle/test_oracle.py
Labels: run-pr-quality-gate

#342 Add RHEL snapshot tests
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:5/cve-2017-3509.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:5/cve-2017-3511.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:5/cve-2017-3526.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:5/cve-2017-3533.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:5/cve-2017-3539.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:5/cve-2017-3544.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:6/cve-2017-3509.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:6/cve-2017-3511.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:6/cve-2017-3526.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:6/cve-2017-3533.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:6/cve-2017-3539.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:6/cve-2017-3544.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:7/cve-2017-3509.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:7/cve-2017-3511.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:7/cve-2017-3526.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:7/cve-2017-3533.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:7/cve-2017-3539.json
  tests/unit/providers/rhel/test-fixtures/snapshots/rhel:7/cve-2017-3544.json
  tests/unit/providers/rhel/test_rhel.py
Labels: run-pr-quality-gate

#347 Add Mariner snapshot tests
  tests/unit/providers/mariner/test-fixtures/snapshots/mariner:2.0/CVE-2022-3736.json
  tests/unit/providers/mariner/test-fixtures/snapshots/mariner:2.0/CVE-2023-21977.json
  tests/unit/providers/mariner/test-fixtures/snapshots/mariner:2.0/CVE-2023-21980.json
  tests/unit/providers/mariner/test_mariner.py
Labels: run-pr-quality-gate

#346 Add GHSA snapshot tests
  tests/unit/providers/github/test-fixtures/snapshots/github:java/ghsa-mh6f-8j2x-4483.json
  tests/unit/providers/github/test-fixtures/snapshots/github:npm/ghsa-mh6f-8j2x-4483.json
  tests/unit/providers/github/test_github.py
Labels: run-pr-quality-gate

#345 Add Wolfi snapshot tests
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2016-2781.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2017-8806.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2018-1000156.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2018-20969.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2018-25032.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2018-6951.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2018-6952.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2019-13636.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2019-13638.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2019-20633.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2019-6293.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2020-10735.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2020-8927.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2021-30218.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2021-30219.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2021-43618.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-1586.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-1587.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-26691.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-27404.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-27405.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-27406.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-28391.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-28506.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-29458.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-30065.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-32221.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-3358.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-3602.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-36227.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-37434.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-3786.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-38126.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-38128.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-38533.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-39046.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-39253.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-39260.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-40303.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-40304.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-40674.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-41716.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-41717.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-41720.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-42010.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-42011.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-42012.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-42916.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-43680.json
  tests/unit/providers/wolfi/test-fixtures/snapshots/wolfi:rolling/CVE-2022-46908.json
  tests/unit/providers/wolfi/test_wolfi.py
Labels: run-pr-quality-gate

#344 Add Ubuntu snapshot tests
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:19.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.10/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-41861.json
  tests/unit/providers/ubuntu/test_ubuntu.py
Labels: run-pr-quality-gate

#343 Add SLES snapshot tests
  tests/unit/providers/sles/test-fixtures/snapshots/sles:15.1/cve-2021-29154.json
  tests/unit/providers/sles/test-fixtures/snapshots/sles:15/cve-2021-29154.json
  tests/unit/providers/sles/test_sles.py
Labels: run-pr-quality-gate

#351 Remove bare "except:" clauses except those that re-raise
  src/vunnel/providers/__init__.py
  src/vunnel/providers/alpine/parser.py
  src/vunnel/providers/rhel/parser.py
  src/vunnel/providers/sles/parser.py
  src/vunnel/providers/ubuntu/git.py
  src/vunnel/providers/ubuntu/parser.py
  src/vunnel/providers/wolfi/parser.py
  src/vunnel/utils/__init__.py
  src/vunnel/utils/oval_parser.py
  src/vunnel/utils/oval_v2.py
Labels: run-pr-quality-gate

#361 chore: remove file noqa from rhel oval parser
  src/vunnel/providers/rhel/oval_parser.py
Labels: run-pr-quality-gate

#355 chore: remove file-scoped noqa from NVD
  src/vunnel/providers/nvd/api.py
  src/vunnel/providers/nvd/manager.py
Labels: run-pr-quality-gate

#366 chore: remove file noqa for utils oval parser
  src/vunnel/utils/oval_parser.py
  tests/quality/config.yaml
Labels: run-pr-quality-gate

#353 chore: Remove file noqa on alpine parser
  src/vunnel/providers/alpine/parser.py
Labels: run-pr-quality-gate

#367 chore: remove file noqa on SLES parser
  src/vunnel/providers/sles/parser.py
Labels: run-pr-quality-gate

#368 chore: remove file noqa from utils OVAL V2 parser
  src/vunnel/utils/oval_v2.py
Labels: run-pr-quality-gate

#374 chore: bump yardstick
  poetry.lock
  pyproject.toml
  tests/quality/configure.py
Labels: run-pr-quality-gate

#373 chore: remove file noqa from utils fdb
  src/vunnel/utils/fdb.py
  tests/quality/config.yaml
Labels: run-pr-quality-gate

#375 chore: remove remaining blanket noqas
  src/vunnel/cli/cli.py
  src/vunnel/providers/amazon/parser.py
  src/vunnel/providers/debian/parser.py
  src/vunnel/providers/github/parser.py
  src/vunnel/providers/oracle/parser.py
  src/vunnel/providers/rhel/parser.py
  src/vunnel/providers/sles/parser.py
  src/vunnel/providers/wolfi/parser.py
  src/vunnel/result.py
  src/vunnel/utils/vulnerability.py
  tests/quality/configure.py
  tests/unit/providers/github/test_github.py
Labels: run-pr-quality-gate

#377 fix: respect GitHub rate limiting
  src/vunnel/providers/github/parser.py
  tests/unit/providers/github/test_github.py
Labels: run-pr-quality-gate
