Repository anchore/vunnel, pull requests merged in 2023-09, with the labels that each got.

#276 chore: bump crane
  Makefile
Labels: dependencies, changelog-ignore

#278 Add description to amazon provider
  src/vunnel/providers/amazon/parser.py
  tests/unit/providers/amazon/test_amazon.py
Labels: run-pr-quality-gate

#303 Notify slack channel on quality gate failures
  .github/workflows/pr-quality-gate.yaml
  tests/quality/README.md
Labels: run-pr-quality-gate

#307 Fix namespace resolution for quality gate testing
  poetry.lock
  pyproject.toml
  src/vunnel/cli/cli.py
  src/vunnel/cli/config.py
  src/vunnel/providers/amazon/parser.py
  src/vunnel/providers/debian/parser.py
  src/vunnel/providers/github/parser.py
  src/vunnel/providers/mariner/parser.py
  src/vunnel/providers/wolfi/parser.py
  src/vunnel/utils/__init__.py
  tests/quality/config.yaml
  tests/quality/configure.py
  tests/quality/gate.py
Labels: run-pr-quality-gate

#314 Use annotated tags + upgrade go action
  .github/actions/bootstrap/action.yaml
  .github/workflows/release.yaml
Labels: changelog-ignore
