Repository anchore/vunnel, pull requests merged in 2023-07, with the labels that each got.

#225 feat: bump ubuntu provider to v2 to ensure rebuild from clean workspace after upstream data changes
  src/vunnel/providers/ubuntu/__init__.py
Labels: enhancement, provider:ubuntu, run-pr-quality-gate

#232 feat: preserve prior results longer with sqlite writer
  src/vunnel/provider.py
  src/vunnel/providers/alpine/__init__.py
  src/vunnel/providers/amazon/__init__.py
  src/vunnel/providers/chainguard/__init__.py
  src/vunnel/providers/debian/__init__.py
  src/vunnel/providers/github/__init__.py
  src/vunnel/providers/mariner/__init__.py
  src/vunnel/providers/nvd/__init__.py
  src/vunnel/providers/oracle/__init__.py
  src/vunnel/providers/rhel/__init__.py
  src/vunnel/providers/sles/__init__.py
  src/vunnel/providers/wolfi/__init__.py
  src/vunnel/result.py
  tests/unit/test_result.py
Labels: run-pr-quality-gate

#242 fix: bump PyYAML to 6.0.1 to address cython compatibility issue
  poetry.lock
  pyproject.toml
Labels: bug, run-pr-quality-gate

#236 fix: add retry on alpine and mariner url fetches
  src/vunnel/providers/alpine/parser.py
  src/vunnel/providers/mariner/parser.py
Labels: bug, run-pr-quality-gate
