Repository anchore/vunnel, pull requests merged in 2024-08, with the labels that each got.

#648 chore: remove unneeded noqa, enable lint for same
  pyproject.toml
  src/vunnel/cli/cli.py
  src/vunnel/provider.py
  src/vunnel/providers/amazon/parser.py
  src/vunnel/providers/github/parser.py
  src/vunnel/providers/nvd/manager.py
  src/vunnel/providers/nvd/overrides.py
  src/vunnel/providers/oracle/parser.py
  src/vunnel/providers/rhel/oval_parser.py
  src/vunnel/providers/rhel/parser.py
  src/vunnel/providers/ubuntu/git.py
  src/vunnel/providers/ubuntu/parser.py
  src/vunnel/providers/wolfi/parser.py
  src/vunnel/schema.py
  src/vunnel/utils/oval_parser.py
Labels: run-pr-quality-gate

#650 fix: grype_db #344 missing CVE/Package associations
  src/vunnel/providers/sles/parser.py
  tests/unit/providers/sles/test-fixtures/snapshots/sles:15/cve-2010-1323.json
  tests/unit/providers/sles/test-fixtures/suse_truncated.xml
  tests/unit/providers/sles/test_sles.py
Labels: bug, run-pr-quality-gate

#673 chore: remove support for python 3.9, 3.10
  .github/workflows/validations.yaml
  poetry.lock
  pyproject.toml
  src/vunnel/distribution.py
  src/vunnel/provider.py
  src/vunnel/providers/__init__.py
  src/vunnel/providers/github/parser.py
  src/vunnel/providers/nvd/manager.py
  src/vunnel/utils/oval_parser.py
  src/vunnel/utils/oval_v2.py
  tox.ini
Labels: changelog-ignore, run-pr-quality-gate
