Repository anchore/vunnel, pull requests merged in 2024-01, with the labels that each got.

#437 feat(oracle): extract description from Oracle Security Advisories
  src/vunnel/utils/oval_parser.py
  tests/unit/providers/oracle/test-fixtures/snapshots/ol:5/elsa-2007-0057.json
  tests/unit/providers/oracle/test-fixtures/snapshots/ol:6/elsa-2018-4250.json
  tests/unit/providers/oracle/test_oracle.py
Labels: enhancement, run-pr-quality-gate

#438 Alleviate RHEL provider CVE-list race condition
  src/vunnel/providers/rhel/parser.py
Labels: bug, run-pr-quality-gate

#445 chore(rhel): filter by product name when retrieving summary cves
  src/vunnel/providers/rhel/parser.py
Labels: run-pr-quality-gate

#448 hack: hard-code severity for debian CVE-2023-44487
  src/vunnel/providers/debian/parser.py
Labels: run-pr-quality-gate

#451 fix(ubuntu): update vulnerability urls
  src/vunnel/providers/ubuntu/parser.py
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:14.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:16.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:18.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:19.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:20.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:21.10/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.04/cve-2022-41861.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2019-17185.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2021-4204.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-20566.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-41859.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-41860.json
  tests/unit/providers/ubuntu/test-fixtures/snapshots/ubuntu:22.10/cve-2022-41861.json
Labels: bug, run-pr-quality-gate
