Repository anchore/vunnel, pull requests merged in 2024-11, with the labels that each got.

#730 Add processor to workspace state
  .gitignore
  .pre-commit-config.yaml
  schema/provider-workspace-state/schema-1.0.3.json
  src/vunnel/schema.py
  src/vunnel/workspace.py
Labels: enhancement

#731 docs: note Azure Linux in README
  README.md
Labels: documentation

#739 Add switch to bypass quality gate
  .github/workflows/release.yaml
Labels: changelog-ignore

#738 Wire up retry count config to NVD provider
  src/vunnel/providers/nvd/__init__.py
  src/vunnel/providers/nvd/api.py
  src/vunnel/providers/nvd/manager.py
  src/vunnel/providers/nvd/overrides.py
  src/vunnel/utils/http.py
  tests/unit/cli/test-fixtures/full.yaml
  tests/unit/cli/test_cli.py
  tests/unit/cli/test_config.py
  tests/unit/providers/nvd/test_api.py
  tests/unit/utils/test_http.py
Labels: enhancement, run-pr-quality-gate
