Repository anchore/vunnel, pull requests merged in 2025-03, with the labels that each got.

#779 Fix v6 archive extension
  .github/scripts/update-dev-db.sh
  poetry.lock
  pyproject.toml
  tests/quality/Makefile
  tests/quality/config.yaml
  tests/quality/configure.py
  tests/quality/validate-namespaces.py
Labels: bug, run-pr-quality-gate

#512 feat: add Bitnami as new provider
  DEVELOPING.md
  schema/vulnerability/osv/schema-1.5.0.json
  src/vunnel/cli/config.py
  src/vunnel/providers/__init__.py
  src/vunnel/providers/bitnami/__init__.py
  src/vunnel/providers/bitnami/git.py
  src/vunnel/providers/bitnami/parser.py
  src/vunnel/providers/github/__init__.py
  src/vunnel/providers/ubuntu/parser.py
  tests/unit/cli/test_cli.py
  tests/unit/providers/bitnami/test-fixtures/vulndb/data/brotli/BIT-brotli-2020-8927.json
  tests/unit/providers/bitnami/test-fixtures/vulndb/data/consul/BIT-consul-2021-37219.json
  tests/unit/providers/bitnami/test_bitnami.py
  tests/unit/test_provider.py
Labels: run-pr-quality-gate

#788 feat: add ubuntu 25.04 codename to version mapping
  src/vunnel/providers/ubuntu/parser.py
Labels: run-pr-quality-gate

#790 chore: rename http to http_wrapper
  src/vunnel/provider.py
  src/vunnel/providers/alpine/parser.py
  src/vunnel/providers/amazon/parser.py
  src/vunnel/providers/debian/parser.py
  src/vunnel/providers/kev/manager.py
  src/vunnel/providers/mariner/parser.py
  src/vunnel/providers/nvd/api.py
  src/vunnel/providers/nvd/overrides.py
  src/vunnel/providers/oracle/parser.py
  src/vunnel/providers/rhel/csaf_client.py
  src/vunnel/providers/rhel/parser.py
  src/vunnel/providers/sles/parser.py
  src/vunnel/providers/wolfi/parser.py
  src/vunnel/utils/http_wrapper.py
  tests/conftest.py
  tests/unit/providers/amazon/test_amazon.py
  tests/unit/providers/kev/test_kev.py
  tests/unit/providers/nvd/test_api.py
  tests/unit/providers/rhel/test_csaf_client.py
  tests/unit/utils/test_http_wrapper.py
Labels: changelog-ignore, run-pr-quality-gate

#791 feat: alma linux OSV provider
  schema/vulnerability/osv/schema-1.7.0.json
  src/vunnel/cli/config.py
  src/vunnel/providers/__init__.py
  src/vunnel/providers/alma/__init__.py
  src/vunnel/providers/alma/git.py
  src/vunnel/providers/alma/parser.py
  tests/unit/cli/test_cli.py
  tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux8/ALBA-2021:4378.json
  tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux8/ALSA-2023:4520.json
  tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux9/ALSA-2022:8194.json
  tests/unit/providers/alma/test-fixtures/osv-database/advisories/almalinux9/ALSA-2024:2433.json
  tests/unit/providers/alma/test_alma.py
  tests/unit/test_provider.py
Labels: run-pr-quality-gate

#794 feat: rocky linux OSV provider
  schema/vulnerability/osv/schema-1.3.1.json
  src/vunnel/cli/config.py
  src/vunnel/providers/__init__.py
  src/vunnel/providers/rocky/__init__.py
  src/vunnel/providers/rocky/client.py
  src/vunnel/providers/rocky/parser.py
  tests/unit/cli/test_cli.py
  tests/unit/providers/alma/test_alma.py
  tests/unit/providers/rocky/test-fixtures/osv/RLSA-2021_3891.json
  tests/unit/providers/rocky/test-fixtures/osv/RLSA-2023_3220.json
  tests/unit/providers/rocky/test-fixtures/osv/RLSA-2024_3671.json
  tests/unit/providers/rocky/test_rocky.py
  tests/unit/test_provider.py
Labels: enhancement, run-pr-quality-gate

#784 Port from poetry to uv
  .binny.yaml
  .github/actions/bootstrap/action.yaml
  .github/actions/quality-gate/action.yaml
  .github/dependabot.yml
  .github/scripts/ci-check.sh
  .github/scripts/dev-shell.sh
  .github/scripts/update-dev-db.sh
  .github/workflows/nightly-quality-gate.yaml
  .github/workflows/pr-quality-gate.yaml
  .github/workflows/release.yaml
  .github/workflows/validations.yaml
  .gitignore
  .pre-commit-config.yaml
  DEVELOPING.md
  Makefile
  Taskfile.yaml
  example/README.md
  poetry.lock
  pyproject.toml
  tests/quality/Makefile
  tests/quality/config.yaml
  tox.ini
  uv.lock
Labels: changelog-ignore, run-pr-quality-gate

#802 feat: add skip download CLI option
  src/vunnel/cli/cli.py
  src/vunnel/provider.py
  src/vunnel/providers/rocky/__init__.py
  src/vunnel/providers/rocky/client.py
  src/vunnel/providers/rocky/parser.py
  tests/unit/cli/test_cli.py
  tests/unit/providers/rocky/test_rocky.py
Labels: enhancement

#804 feat: enable skipping downloads in RHEL provider
  src/vunnel/providers/rhel/__init__.py
  src/vunnel/providers/rhel/csaf_client.py
  src/vunnel/providers/rhel/parser.py
  src/vunnel/providers/rhel/rhsa_provider.py
  tests/unit/providers/rhel/test-fixtures/csaf/input/cve/full/.gitkeep
  tests/unit/providers/rhel/test-fixtures/csaf/input/cve/min/.gitkeep
  tests/unit/providers/rhel/test-fixtures/csaf/input/cve/min_pages/1.json
  tests/unit/providers/rhel/test_rhel.py
Labels: enhancement, run-pr-quality-gate
